// Generated by create-allthing
// Declarative pipeline: dev → staging → prod with manual approval

pipeline {
    agent any

    environment {
        POSTGRES_USER     = credentials('db-credentials').username
        POSTGRES_PASSWORD  = credentials('db-credentials').password
        POSTGRES_DB        = 'appdb'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Frontend') {
            steps {
                dir('frontend') {
                    sh 'npm ci && npm run build'
                }
            }
        }

        stage('Build Backend') {
            steps {
                dir('backend') {
                    sh 'pip install uv && uv sync'
                }
            }
        }

        stage('Test Backend') {
            steps {
                dir('backend') {
                    sh 'uv run pytest'
                }
            }
        }

        stage('Docker Build') {
            steps {
                sh 'docker compose build'
            }
        }

        stage('Deploy to Dev') {
            steps {
                echo 'Deploying to dev environment...'
                sh '''
                    docker compose -f docker-compose.yml \
                        --project-name dev \
                        up -d --build
                '''
            }
        }

        stage('Deploy to Staging') {
            steps {
                echo 'Deploying to staging environment...'
                sh '''
                    docker compose -f docker-compose.yml \
                        --project-name staging \
                        up -d --build
                '''
            }
        }

        stage('Deploy to Prod') {
            when {
                branch 'main'
            }
            input {
                message 'Approve deploy to production?'
                ok 'Deploy'
            }
            steps {
                echo 'Deploying to production...'
                sh '''
                    docker compose -f docker-compose.yml \
                        --project-name prod \
                        up -d --build
                '''
            }
        }
    }

    post {
        always {
            echo 'Pipeline finished.'
        }
        failure {
            echo 'Pipeline failed — check the logs above.'
        }
        success {
            echo 'Pipeline completed successfully.'
        }
    }
}
